version: '3'
services:
  prod:
    build:
      context: '.'
      args:
        REQIREMENTS_FILE: './prod-requirements.txt'
        STARTING_DIR: '/app'
    volumes:
      - ./app:/app
    image: my-data-science-app-prod
