site_name: 'Data Science Project Template'
repo_url: https://github.com/mark-curran/data-science-project-template
remote_branch: gh-pages

nav:
    - 'index.md'
    - 'license.md'
    - 'using_mkdocs.md'
