site_name: 'Data Science Project Template'
repo_url: https://github.com/mark-curran/data-science-project-template
remote_branch: gh-pages
theme: readthedocs

nav:
    - Home: 'index.md'
    - Quickstart:
        - 'quickstart/quickstart.md'
    - Design:
        - 'design/design.md'
    - Additional Features:
        - 'additional_features/accessing_credentials.md'
        - 'additional_features/vscode_extensions.md'
        - 'additional_features/jupyterlab.md'
        - 'additional_features/editing_requirements.md'
        - 'additional_features/unit_tests.md'
        - 'additional_features/users_inside_container.md'
        - 'additional_features/using_mkdocs.md'
    - About:
        - 'about/about.md'
