
name: Build Documentation using MkDocs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]

jobs:
  build-deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        working-directory: docs
        run: |
          python -m pip install --upgrade pip
          pip install -r docs-requirements.txt

      - name: Deploy
        working-directory: docs
        run: |
          git pull
          mkdocs build
          mkdocs gh-deploy